#!/bin/bash
SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
echo ${SCRIPT_DIR}
ROOT_DIR="$( realpath "${SCRIPT_DIR}/.." )"
echo ${ROOT_DIR}
CONFIGS_DIR="$( realpath "${SCRIPT_DIR}/../config" )"
echo ${CONFIGS_DIR}
BUILD_DIR="${ROOT_DIR}/build"
echo ${BUILD_DIR}
SKATEBOARD_DEFCONFIG="${CONFIGS_DIR}/buildroot/configs/skateboard_defconfig"
echo ${SKATEBOARD_DEFCONFIG}
BR2_LINUX_KERNEL_VERSION="$( grep -Po 'BR2_LINUX_KERNEL_VERSION=\"\K[^\"]*' ${SKATEBOARD_DEFCONFIG})"
echo ${BR2_LINUX_KERNEL_VERSION}
BUILDROOT_BUILD_DIR="${ROOT_DIR}/build/buildroot/src/buildroot-build"
echo ${BUILDROOT_BUILD_DIR}
SYSROOT="$( realpath "$( find ${BUILDROOT_BUILD_DIR}/host -name sysroot -print )" )" 
echo ${SYSROOT}
VMLINUX_DIR="${BUILDROOT_BUILD_DIR}/build/linux-${BR2_LINUX_KERNEL_VERSION}"
VMLINUX_PATH="${VMLINUX_DIR}/vmlinux"
GDBINIT_DIR="${BUILD_DIR}/gdbinit"
mkdir -p ${GDBINIT_DIR}
GDBINIT_PATH="${GDBINIT_DIR}/gdbinit"
GDB_PATH="${BUILDROOT_BUILD_DIR}/host/bin/arm-linux-gdb"
echo ${GDB_PATH}
echo "set sysroot ${SYSROOT}" > ${GDBINIT_PATH}
echo "file ${VMLINUX_PATH}" >> ${GDBINIT_PATH}
QEMU_COMMAND="${BUILDROOT_BUILD_DIR}/host/bin/qemu-system-arm -M versatilepb -kernel ${BUILDROOT_BUILD_DIR}/images/zImage -dtb ${BUILDROOT_BUILD_DIR}/images/versatile-pb.dtb -drive format=raw,file=${BUILDROOT_BUILD_DIR}/images/rootfs.ext2 -append \"root=/dev/sda console=ttyAMA0,115200\" -nographic -m 15 -net user -net nic,model=rtl8139"
echo ${QEMU_COMMAND}
