#!/bin/bash
SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
source ${SCRIPT_DIR}/setup-gdbinit
echo
echo
echo
echo "Linux version to be built is:"
echo ${BR2_LINUX_KERNEL_VERSION}
