#!/bin/bash
BUILDROOT_GIT=https://github.com/buildroot/buildroot.git

ECLIPSE_URL=https://www.eclipse.org/downloads/download.php
ECLIPSE_TAR_GZ=/oomph/epp/oxygen/R/eclipse-inst-linux64.tar.gz
ECLIPSE_MIRROR=1
ECLIPSE_FILE=eclipse-inst-linux64.tar.gz

ECLIPSE_INSTALLER=https://raw.githubusercontent.com/budhash/install-eclipse/master/install-eclipse

OPTIND=1

build_buildroot=1
build_eclipse=1

while getopts "h?be" opt; do
    case "$opt" in
    h|\?)
        show_help
        exit 0
        ;;
    b)
        build_buildroot=0
        ;;
    e)
        build_eclipse=0
    esac
done

echo "build_buildroot=$build_buildroot, build_eclipse=$build_eclipse"

if [[ $build_buildroot -eq 1 ]]; then
    git clone $BUILDROOT_GIT
    pushd buildroot
    make qemu_arm_versatile_nommu_defconfig
    make
    popd
fi

if [[ $build_eclipse -eq 1 ]]; then
    mkdir eclipse-installer
    pushd eclipse-installer
    wget -q -O eclipse-install-script $ECLIPSE_INSTALLER
    chmod 755 eclipse-install-script
    patch eclipse-install-script < ../patches/eclipse-installer-linux-redhat.01.patch
    popd
    ./eclipse-installer/eclipse-install-script eclipse
fi

VNC_ADDRESS="$(ifconfig | perl -ne '/\d+\.\d+\.\d+\.\d+/ && print($&) && exit(0)')"
echo "To connect to this container, you can:" 
echo "1. connect via VNC viewer ${VNC_ADDRESS}:5901"
echo "   default password: vncpassword"
echo "2. connect via noVNC HTML5 full client: " 
echo "   http://${VNC_ADDRESS}:6901/vnc.html, default password: vncpassword"
echo "3. connect via noVNC HTML5 lite client: "
echo "   http://${VNC_ADDRESS}:6901/?password=vncpassword"

